version: '3.7'

services:
  app:
    build:
      context: .                  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile      # (Optional) If the Dockerfile has a custom name or location
    ports:
      - "3002:3002"               # Expose port 3002
    environment:
      - NODE_ENV=development      # Example environment variable
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
